name: Common CI workflow

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    strategy:
      matrix:
        ocaml-version:
          - 5.1.0
        node-version:
          - hydrogen
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Build and test
        uses: kxcdev/ocaml-general-gha@v3
        with:
          ocaml-version: ${{ matrix.ocaml-version }}
          node-version: ${{ matrix.node-version }}
          setup-command: "opam install --locked . -y --deps-only --with-test"
          build-command:
            "dune build & cd jsland & yarn & yarn build"
          pr-report-test-result: ${{ matrix.ocaml-version == '5.1.0' }}
